/*
 * Copyright (C) 2026, Advanced Micro Devices. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holder nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 * without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 */

/*
 * cpuid_flags.h - Pure C enums for the CPUID core. Source of truth shared by the
 * C core, the C surface and the C++ surface (whose enum class values mirror these
 * exactly, so casts are identity).
 *
 * IMPORTANT: au_cpuid_flag_t and au_uarch_t MUST stay value-for-value identical
 * to Au::ECpuidFlag and Au::EUarch (SDK/Include/Au/Cpuid/X86Cpu.hh). ECpuidFlag
 * is generated by AUD_DEFINE_ENUM which frames it as { Min=0, <flags 1..K>, Max }
 * -- i.e. flags are 1-based. The list below preserves that exact framing/order.
 */

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

    /*
     * CPU vendor. Values mirror Au::EVendor exactly:
     *   Amd = 1, Intel = 2, Other = 3
     */
    typedef enum au_vendor
    {
        AU_VENDOR_AMD   = 1,
        AU_VENDOR_INTEL = 2,
        AU_VENDOR_OTHER = 3,
    } au_vendor_t;

    /*
     * Processor family ID (the numeric CPUID family), named by the AMD family
     * number (17h/19h/1Ah). One family id spans several micro-architectures --
     * that distinction is carried by au_uarch_t, NOT here:
     *   0x17 (17h): Zen, Zen+, Zen2
     *   0x19 (19h): Zen3, Zen4
     *   0x1A (1Ah): Zen5, Zen6
     *   0x1B (1Bh): Zen6 (future)
     * MAX is the latest known family ID. Values mirror Au::EFamily.
     */
    typedef enum au_family
    {
        AU_FAMILY_UNKNOWN = 0x0,
        AU_FAMILY_17H     = 0x17,
        AU_FAMILY_19H     = 0x19,
        AU_FAMILY_1AH     = 0x1A,
        AU_FAMILY_1BH     = 0x1B,
        AU_FAMILY_MAX     = 0x1B, /* always the latest known family ID */
    } au_family_t;

    /*
     * Micro-architecture. Values mirror Au::EUarch exactly:
     *   Unknown=0, Zen=1, ZenPlus=2, Zen2=3, Zen3=4, Zen4=5, Zen5=6, Zen6=7
     */
    typedef enum au_uarch
    {
        AU_UARCH_UNKNOWN = 0,
        AU_UARCH_ZEN,
        AU_UARCH_ZENPLUS,
        AU_UARCH_ZEN2,
        AU_UARCH_ZEN3,
        AU_UARCH_ZEN4,
        AU_UARCH_ZEN5,
        AU_UARCH_ZEN6,
        AU_UARCH_MAX = AU_UARCH_ZEN6,
    } au_uarch_t;

    /*
     * CPU feature flags. Mirrors Au::ECpuidFlag value-for-value (AUD_DEFINE_ENUM
     * framing: MIN=0, flags start at 1, MAX last).
     *
     * Single source of truth: AU_CPUID_FLAG_LIST is an X-macro listing every flag
     * name in ECpuidFlag order. The enum below and the name->flag table used by
     * au_cpuid_flag_from_string() are both generated from it, so they can never
     * drift. Do NOT reorder -- the values are the bitmap indices, the CPUID_MAP
     * feature ids, and (1-based) match ECpuidFlag exactly. The name string for
     * each entry (the stringized token) matches what ECpuidFlagfromString expects.
     */
#define AU_CPUID_FLAG_LIST(X)                                                  \
    X(sse3) X(pclmulqdq) X(dtes64) X(monitor) X(dscpl) X(vmx) X(smx) X(est)    \
    X(tm2) X(ssse3) X(cid) X(fma) X(cx16) X(xtpr) X(pdcm) X(pcid) X(dca)       \
    X(sse4_1) X(sse4_2) X(x2apic) X(movbe) X(popcnt) X(tsc_deadline) X(aes)    \
    X(xsave) X(osxsave) X(avx) X(f16c) X(rdrand) X(hypervisor) X(fpu) X(vme)   \
    X(de) X(pse) X(tsc) X(msr) X(pae) X(mce) X(cx8) X(apic) X(sep) X(mtrr)     \
    X(pge) X(mca) X(cmov) X(pat) X(pse36) X(pn) X(clflush) X(ds) X(acpi)       \
    X(mmx) X(fxsr) X(sse) X(sse2) X(ss) X(ht) X(tm) X(ia64) X(pbe) X(arat)     \
    X(fsgsbase) X(tsc_adjust) X(bmi1) X(hle) X(avx2) X(smep) X(bmi2) X(erms)   \
    X(invpcid) X(rtm) X(mpx) X(avx512f) X(avx512dq) X(rdseed) X(adx) X(smap)   \
    X(avx512ifma) X(pcommit) X(clflushopt) X(clwb) X(avx512pf) X(avx512er)     \
    X(avx512cd) X(sha_ni) X(avx512bw) X(avx512vl) X(avx512vbmi) X(umip)        \
    X(pku) X(ospke) X(avx512_vpopcntdq) X(la57) X(rdpid) X(avx512_4vnniw)      \
    X(avx512_4fmaps) X(avx512_bf16) X(avxvnni) X(xsaveopt) X(xsavec)           \
    X(xgetbv1) X(xsaves) X(lahf_lm) X(cmp_legacy) X(svm) X(extapic)            \
    X(cr8legacy) X(abm) X(sse4a) X(misalignsse) X(_3dnowprefetch) X(osvw)      \
    X(ibs) X(xop) X(skinit) X(wdt) X(lwp) X(fma4) X(tce) X(nodeid_msr) X(tbm)  \
    X(topoext) X(perfctr_core) X(perfctr_nb) X(syscall) X(nxxd) X(mmxext)      \
    X(fxsr_opt) X(pdpe1gb) X(rdtscp) X(lmi64) X(_3dnowext) X(_3dnow) X(invtsc) \
    X(npt) X(lbrv) X(svm_lock) X(nrip_save) X(tsc_scale) X(vmcb_clean)         \
    X(flushbyasid) X(decodeassists) X(pause_filter) X(pfthreshold) X(xstore)   \
    X(xstore_en) X(xcrypt) X(xcrypt_en) X(ace2) X(ace2_en) X(phe) X(phe_en)    \
    X(pmm) X(pmm_en) X(vaes) X(vpclmulqdq) X(avx512_vnni) X(avx512_bitalg)     \
    X(avx512vbmi2) X(movdiri) X(movdir64b) X(avx512_vpintersect) X(x2avic)     \
    X(clzero) X(avx512_bmm) X(avx512_fp16) X(avx_ifma) X(avx_vnni_int8)        \
    X(avx_ne_convert) X(avx_vnni_int16) X(avx10)

    typedef enum au_cpuid_flag
    {
        AU_FLAG_MIN = 0,
#define AU_CPUID_FLAG_ENUM(name) AU_FLAG_##name,
        AU_CPUID_FLAG_LIST(AU_CPUID_FLAG_ENUM)
#undef AU_CPUID_FLAG_ENUM
        AU_FLAG_MAX,
    } au_cpuid_flag_t;

#ifdef __cplusplus
} /* extern "C" */
#endif
